name: manual release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        # overriding some of the basic behaviors to just get the changelog
        with:
          git-user-name: Tiago Nascimento
          github-token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
          # always do the release, even if there are no semantic commits
          skip-on-empty: false
          tag-prefix: ''
      - name: Create Github Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          make_latest: true
