name: publish

on:
  release:
    types: [released]
  # support manual release in case something goes wrong and needs to be repeated or tested
  workflow_dispatch:
    inputs:
      tag:
        description: github tag that needs to publish
        type: string
        required: true
      npmTag:
        description: npm dist-tag to publish under
        type: string
        required: false
        default: latest
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TAG: ${{ github.event.release.tag_name || inputs.tag }}
      NPM_TAG: ${{ inputs.npmTag || 'latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_TAG }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install --network-timeout 600000
      - run: yarn build
      - run: npm install --global @salesforce/plugin-release-management@5
      - run: |
          sf-release npm:package:release \
            --githubtag "$GITHUB_TAG" \
            --npmtag "$NPM_TAG" \
            --no-install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
